/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;
import com.mycompany.mavenproject1.App;
import javax.swing.*;
/**
 *
 * @author jogar
 */
public class AdminJPanel extends javax.swing.JPanel {

   private App app;  // ✅ Mantém a referência ao App para controle do CardLayout

    // ✅ Construtor ajustado para receber App
    public AdminJPanel(App app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BemVindojLabel1 = new javax.swing.JLabel();
        CadastrarUsuariosjButton1 = new javax.swing.JButton();
        VisalizarUsuariojButton2 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));

        BemVindojLabel1.setText("Bem Vindo!");

        CadastrarUsuariosjButton1.setText("Cadastrar Usuários");
        CadastrarUsuariosjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuariosjButton1ActionPerformed(evt);
            }
        });

        VisalizarUsuariojButton2.setText("Visualizar Usuários");
        VisalizarUsuariojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisalizarUsuariojButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastrarUsuariosjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisalizarUsuariojButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BemVindojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BemVindojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(CadastrarUsuariosjButton1)
                .addGap(18, 18, 18)
                .addComponent(VisalizarUsuariojButton2)
                .addGap(0, 238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarUsuariosjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuariosjButton1ActionPerformed
        app.getCardLayout().show(app.getContainer(), "CadUsuario");
    }//GEN-LAST:event_CadastrarUsuariosjButton1ActionPerformed

    private void VisalizarUsuariojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisalizarUsuariojButton2ActionPerformed
        app.getCardLayout().show(app.getContainer(), "ConsultUsuario");
    }//GEN-LAST:event_VisalizarUsuariojButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindojLabel1;
    private javax.swing.JButton CadastrarUsuariosjButton1;
    private javax.swing.JButton VisalizarUsuariojButton2;
    // End of variables declaration//GEN-END:variables
}
