/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;
import com.mycompany.mavenproject1.App;
import javax.swing.*;
/**
 *
 * @author jogar
 */
public class AdminJPanel extends javax.swing.JPanel {

   private App app;  // ✅ Mantém a referência ao App para controle do CardLayout

    // ✅ Construtor ajustado para receber App
    public AdminJPanel(App app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastrarUsuariosjButton1 = new javax.swing.JButton();
        VisalizarUsuariojButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BemVindojLabel1 = new javax.swing.JLabel();
        deslogarjButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(600, 400));

        CadastrarUsuariosjButton1.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        CadastrarUsuariosjButton1.setText("Cadastrar Usuários");
        CadastrarUsuariosjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuariosjButton1ActionPerformed(evt);
            }
        });

        VisalizarUsuariojButton2.setFont(new java.awt.Font("SansSerif", 3, 20)); // NOI18N
        VisalizarUsuariojButton2.setText("Visualizar Usuários");
        VisalizarUsuariojButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisalizarUsuariojButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(31, 79, 144));

        BemVindojLabel1.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        BemVindojLabel1.setForeground(new java.awt.Color(255, 255, 255));
        BemVindojLabel1.setText("Área do Administrador");

        deslogarjButton1.setBackground(new java.awt.Color(212, 51, 51));
        deslogarjButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        deslogarjButton1.setForeground(new java.awt.Color(255, 255, 255));
        deslogarjButton1.setText("Deslogar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BemVindojLabel1)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(deslogarjButton1)
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(BemVindojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deslogarjButton1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(31, 79, 144));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisalizarUsuariojButton2)
                    .addComponent(CadastrarUsuariosjButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(CadastrarUsuariosjButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VisalizarUsuariojButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarUsuariosjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuariosjButton1ActionPerformed
        app.getCardLayout().show(app.getContainer(), "CadUsuario");
    }//GEN-LAST:event_CadastrarUsuariosjButton1ActionPerformed

    private void VisalizarUsuariojButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisalizarUsuariojButton2ActionPerformed
        app.getConsultarUsuariosJPanel().carregarUsuariosNaTabela();
        
        app.getCardLayout().show(app.getContainer(), "ConsultUsuario");

    }//GEN-LAST:event_VisalizarUsuariojButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindojLabel1;
    private javax.swing.JButton CadastrarUsuariosjButton1;
    private javax.swing.JButton VisalizarUsuariojButton2;
    private javax.swing.JButton deslogarjButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
