/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;

import javax.swing.JOptionPane;
import com.mycompany.mavenproject1.App;
/**
 *
 * @author jogar
 */
public class CadastroLivroJPanel extends javax.swing.JPanel {

    private App app;
    
    public CadastroLivroJPanel(App app) {
        this.app = app;
        initComponents();
    }

    private boolean validarCampos() {
        if (EntradaTitulojTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Título do livro é obrigatório.");
        
            return false;
        }
        if (EntradaAutorjTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Autor é obrigatório.");
        
            return false; // Impede o salvamento se nenhuma checkbox estiver selecionada
        }
        
            return true;
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EntradaTitulojTextField1 = new javax.swing.JTextField();
        AutorjLabel2 = new javax.swing.JLabel();
        EntradaAutorjTextField1 = new javax.swing.JTextField();
        TipoLivrojLabel2 = new javax.swing.JLabel();
        TipoLivrojComboBox1 = new javax.swing.JComboBox<>();
        SalvarLivrojButton1 = new javax.swing.JButton();
        CancelarLivrojButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Título do Livro");

        EntradaTitulojTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTitulojTextField1ActionPerformed(evt);
            }
        });

        AutorjLabel2.setText("Autor");

        EntradaAutorjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaAutorjTextField1ActionPerformed(evt);
            }
        });

        TipoLivrojLabel2.setText("Tipo do Livro");

        TipoLivrojComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciência e Sociedade", "Sustentabilidade", "Tecnologia" }));

        SalvarLivrojButton1.setText("Salvar");
        SalvarLivrojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarLivrojButton1ActionPerformed(evt);
            }
        });

        CancelarLivrojButton1.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SalvarLivrojButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(EntradaTitulojTextField1)
                            .addComponent(AutorjLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(EntradaAutorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TipoLivrojLabel2)
                        .addComponent(TipoLivrojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addComponent(CancelarLivrojButton1)
                .addContainerGap(318, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(EntradaTitulojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AutorjLabel2)
                .addGap(18, 18, 18)
                .addComponent(EntradaAutorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TipoLivrojLabel2)
                .addGap(18, 18, 18)
                .addComponent(TipoLivrojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarLivrojButton1)
                    .addComponent(CancelarLivrojButton1))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaTitulojTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTitulojTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTitulojTextField1ActionPerformed

    private void SalvarLivrojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarLivrojButton1ActionPerformed
        if (validarCampos()) {
           JOptionPane.showMessageDialog(this, "Livro salvo com sucesso!");
           
           app.getCardLayout().show(app.getContainer(), "Usuario");
    }//GEN-LAST:event_SalvarLivrojButton1ActionPerformed
    }
    private void EntradaAutorjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaAutorjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaAutorjTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorjLabel2;
    private javax.swing.JButton CancelarLivrojButton1;
    private javax.swing.JTextField EntradaAutorjTextField1;
    private javax.swing.JTextField EntradaTitulojTextField1;
    private javax.swing.JButton SalvarLivrojButton1;
    private javax.swing.JComboBox<String> TipoLivrojComboBox1;
    private javax.swing.JLabel TipoLivrojLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
