package com.mycompany.mavenproject1.view;

/**
 *
 * @author Caua
 */
public class CadastroUsuarioJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuarioJFrame
     */
    public CadastroUsuarioJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CadastroNomejPanel1 = new javax.swing.JPanel();
        nomejLabel1 = new javax.swing.JLabel();
        entradaNomejTextField1 = new javax.swing.JTextField();
        idadejLabel1 = new javax.swing.JLabel();
        entradaIdadejTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TipoUsuarioCadjComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        SustentabilidadejCheckBox1 = new javax.swing.JCheckBox();
        TecnologiajCheckBox2 = new javax.swing.JCheckBox();
        CienciaESociedadejCheckBox3 = new javax.swing.JCheckBox();
        SalvarCadastroUjButton1 = new javax.swing.JButton();
        CancelarCadastroUjButton2 = new javax.swing.JButton();
        CadastroLivrojPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        EntradaTituloLivrojTextField1 = new javax.swing.JTextField();
        autorjLabel4 = new javax.swing.JLabel();
        EntradaAutorjTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoLivroCadLjComboBox1 = new javax.swing.JComboBox<>();
        SalvarCadLivrojButton1 = new javax.swing.JButton();
        CancelarCadLivrojButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomejLabel1.setText("Nome Completo");

        idadejLabel1.setText("Idade");

        entradaIdadejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaIdadejTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de Usuário");

        TipoUsuarioCadjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuário comum", " " }));
        TipoUsuarioCadjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUsuarioCadjComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Livros");

        SustentabilidadejCheckBox1.setText("Sustentabilidade");
        SustentabilidadejCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SustentabilidadejCheckBox1ActionPerformed(evt);
            }
        });

        TecnologiajCheckBox2.setText("Tecnologia");

        CienciaESociedadejCheckBox3.setText("Ciência e Sociedade");

        SalvarCadastroUjButton1.setText("Salvar");

        CancelarCadastroUjButton2.setText("Cancelar");

        javax.swing.GroupLayout CadastroNomejPanel1Layout = new javax.swing.GroupLayout(CadastroNomejPanel1);
        CadastroNomejPanel1.setLayout(CadastroNomejPanel1Layout);
        CadastroNomejPanel1Layout.setHorizontalGroup(
            CadastroNomejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroNomejPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastroNomejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroNomejPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(SalvarCadastroUjButton1)
                        .addGap(43, 43, 43)
                        .addComponent(CancelarCadastroUjButton2))
                    .addGroup(CadastroNomejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(entradaNomejTextField1)
                        .addComponent(nomejLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addComponent(idadejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entradaIdadejTextField1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(TipoUsuarioCadjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SustentabilidadejCheckBox1)
                    .addComponent(TecnologiajCheckBox2)
                    .addComponent(CienciaESociedadejCheckBox3))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        CadastroNomejPanel1Layout.setVerticalGroup(
            CadastroNomejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroNomejPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nomejLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaNomejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idadejLabel1)
                .addGap(18, 18, 18)
                .addComponent(entradaIdadejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoUsuarioCadjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SustentabilidadejCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TecnologiajCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CienciaESociedadejCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastroNomejPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarCadastroUjButton1)
                    .addComponent(CancelarCadastroUjButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel3.setText("Título do Livro");

        autorjLabel4.setText("Autor");

        jLabel4.setText("Tipo de Livro");

        tipoLivroCadLjComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ciência e Sociedade", "Sustentabilidade", "Tecnologia", " " }));

        SalvarCadLivrojButton1.setText("Salvar");
        SalvarCadLivrojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarCadLivrojButton1ActionPerformed(evt);
            }
        });

        CancelarCadLivrojButton2.setText("Cancelar");

        javax.swing.GroupLayout CadastroLivrojPanel2Layout = new javax.swing.GroupLayout(CadastroLivrojPanel2);
        CadastroLivrojPanel2.setLayout(CadastroLivrojPanel2Layout);
        CadastroLivrojPanel2Layout.setHorizontalGroup(
            CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLivrojPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastroLivrojPanel2Layout.createSequentialGroup()
                        .addGroup(CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipoLivroCadLjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(autorjLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(EntradaTituloLivrojTextField1)
                                .addComponent(EntradaAutorjTextField1)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(CadastroLivrojPanel2Layout.createSequentialGroup()
                        .addComponent(SalvarCadLivrojButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(CancelarCadLivrojButton2)
                        .addGap(57, 57, 57))))
        );
        CadastroLivrojPanel2Layout.setVerticalGroup(
            CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroLivrojPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaTituloLivrojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(autorjLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaAutorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tipoLivroCadLjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(CadastroLivrojPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarCadLivrojButton1)
                    .addComponent(CancelarCadLivrojButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastroNomejPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(CadastroLivrojPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastroLivrojPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastroNomejPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entradaIdadejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaIdadejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaIdadejTextField1ActionPerformed

    private void TipoUsuarioCadjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUsuarioCadjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoUsuarioCadjComboBox1ActionPerformed

    private void SustentabilidadejCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SustentabilidadejCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SustentabilidadejCheckBox1ActionPerformed

    private void SalvarCadLivrojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarCadLivrojButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalvarCadLivrojButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuarioJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuarioJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CadastroLivrojPanel2;
    private javax.swing.JPanel CadastroNomejPanel1;
    private javax.swing.JButton CancelarCadLivrojButton2;
    private javax.swing.JButton CancelarCadastroUjButton2;
    private javax.swing.JCheckBox CienciaESociedadejCheckBox3;
    private javax.swing.JTextField EntradaAutorjTextField1;
    private javax.swing.JTextField EntradaTituloLivrojTextField1;
    private javax.swing.JButton SalvarCadLivrojButton1;
    private javax.swing.JButton SalvarCadastroUjButton1;
    private javax.swing.JCheckBox SustentabilidadejCheckBox1;
    private javax.swing.JCheckBox TecnologiajCheckBox2;
    private javax.swing.JComboBox<String> TipoUsuarioCadjComboBox1;
    private javax.swing.JLabel autorjLabel4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField entradaIdadejTextField1;
    private javax.swing.JTextField entradaNomejTextField1;
    private javax.swing.JLabel idadejLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel nomejLabel1;
    private javax.swing.JComboBox<String> tipoLivroCadLjComboBox1;
    // End of variables declaration//GEN-END:variables
}
