/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;

import javax.swing.JOptionPane;

import com.mycompany.mavenproject1.*;
import com.mycompany.mavenproject1.dao.LivrosLidosDAO;
import com.mycompany.mavenproject1.model.LivrosLidos;
import com.mycompany.mavenproject1.model.TipoLivro;
import com.mycompany.mavenproject1.model.Users;

public class CadastroLivroJPanel extends javax.swing.JPanel {

    private App app;

    public CadastroLivroJPanel(App app) {
        this.app = app;
        initComponents();
    }

    private boolean validarCampos() {
        if (EntradaTitulojTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Título do livro é obrigatório.");
            return false;
        }
        if (EntradaAutorjTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Autor é obrigatório.");
            return false; 
        }
        if (TipoLivrojComboBox1.getSelectedItem().equals("Selecione...")){
            JOptionPane.showMessageDialog(this, "Coloque um tipo de livro");
            return false;
        }
        return true;
    }
    private void limparCampos() {
        EntradaTitulojTextField1.setText("");
        EntradaAutorjTextField1.setText("");
        TipoLivrojComboBox1.setSelectedItem("Selecione...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        EntradaTitulojTextField1 = new javax.swing.JTextField();
        AutorjLabel2 = new javax.swing.JLabel();
        EntradaAutorjTextField1 = new javax.swing.JTextField();
        TipoLivrojLabel2 = new javax.swing.JLabel();
        TipoLivrojComboBox1 = new javax.swing.JComboBox<>();
        SalvarLivrojButton1 = new javax.swing.JButton();
        CancelarLivrojButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 79, 144));
        setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Título do Livro");

        EntradaTitulojTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EntradaTitulojTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaTitulojTextField1ActionPerformed(evt);
            }
        });

        AutorjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AutorjLabel2.setForeground(new java.awt.Color(255, 255, 255));
        AutorjLabel2.setText("Autor");

        EntradaAutorjTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        EntradaAutorjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaAutorjTextField1ActionPerformed(evt);
            }
        });

        TipoLivrojLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TipoLivrojLabel2.setForeground(new java.awt.Color(255, 255, 255));
        TipoLivrojLabel2.setText("Tipo do Livro");

        TipoLivrojComboBox1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        TipoLivrojComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Cinema e Fotografia", "Autoajuda", "Aventura", "Ciência e Sociedade", "Direito", "Fantasia", "Filosofia", "História", "Poesia", "Política", "Romance", "Sustentabilidade", "Tecnologia", "Terror", "Turismo e Viagem" }));

        SalvarLivrojButton1.setBackground(new java.awt.Color(87, 176, 109));
        SalvarLivrojButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        SalvarLivrojButton1.setForeground(new java.awt.Color(255, 255, 255));
        SalvarLivrojButton1.setText("Salvar");
        SalvarLivrojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarLivrojButton1ActionPerformed(evt);
            }
        });

        CancelarLivrojButton1.setBackground(new java.awt.Color(212, 51, 51));
        CancelarLivrojButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        CancelarLivrojButton1.setForeground(new java.awt.Color(255, 255, 255));
        CancelarLivrojButton1.setText("Cancelar");
        CancelarLivrojButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarLivrojButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AutorjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TipoLivrojLabel2)
                            .addComponent(TipoLivrojComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntradaAutorjTextField1)
                            .addComponent(EntradaTitulojTextField1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(SalvarLivrojButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(CancelarLivrojButton1)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaTitulojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(AutorjLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaAutorjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TipoLivrojLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoLivrojComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarLivrojButton1)
                    .addComponent(CancelarLivrojButton1))
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaTitulojTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaTitulojTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaTitulojTextField1ActionPerformed

    private void SalvarLivrojButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!validarCampos()) {
            return;
        }

        String tituloLivro = EntradaTitulojTextField1.getText().trim();
        String autorLivro = EntradaAutorjTextField1.getText().trim();
        int idUsuarioLogado = Sessao.getIdUsuario();
        
        int tipoLivro = 0;

        if (TipoLivrojComboBox1.getSelectedItem().equals("Cinema e Fotografia")) {
            tipoLivro = 1;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Autoajuda")) {
            tipoLivro = 2;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Aventura")) {
            tipoLivro = 3; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Ciência e Sociedade")) {
            tipoLivro = 4;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Direito")) {
            tipoLivro = 5; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Fantasia")) {
            tipoLivro = 6;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Filosofia")) {
            tipoLivro = 7; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("História")) {
            tipoLivro = 8;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Poesia")) {
            tipoLivro = 9; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Política")) {
            tipoLivro = 10;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Romance")) {
            tipoLivro = 11; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Sustentabilidade")) {
            tipoLivro = 12;
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Tecnologia")) {
            tipoLivro = 13; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Terror")) {
            tipoLivro = 14; 
        } else if (TipoLivrojComboBox1.getSelectedItem().equals("Turismo e Viagem")) {
            tipoLivro = 15; 
        } 
        
        if (tipoLivro == 0) {
            JOptionPane.showMessageDialog(this,
            "Tipo de livro não reconhecido. Selecione um valor válido.");
            return;
        }

        LivrosLidos livrosLidos = new LivrosLidos(0, tituloLivro, autorLivro, tipoLivro, idUsuarioLogado);
        LivrosLidosDAO LivrosDao = new LivrosLidosDAO();

         try {
            LivrosDao.inserir(livrosLidos);
            JOptionPane.showMessageDialog(null, "Livro cadastrado com sucesso!!!");
            limparCampos();
            app.getCardLayout().show(app.getContainer(), "Usuario");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar livro. \n erro: " + e.getMessage());
        }
    }

    private void EntradaAutorjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaAutorjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaAutorjTextField1ActionPerformed

    private void CancelarLivrojButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarLivrojButton1ActionPerformed
        app.getCardLayout().show(app.getContainer(), "Usuario");
    }//GEN-LAST:event_CancelarLivrojButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AutorjLabel2;
    private javax.swing.JButton CancelarLivrojButton1;
    private javax.swing.JTextField EntradaAutorjTextField1;
    private javax.swing.JTextField EntradaTitulojTextField1;
    private javax.swing.JButton SalvarLivrojButton1;
    private javax.swing.JComboBox<String> TipoLivrojComboBox1;
    private javax.swing.JLabel TipoLivrojLabel2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
