package com.mycompany.mavenproject1.view;

import com.mycompany.mavenproject1.App;
import com.mycompany.mavenproject1.dao.UsuarioDAO;
import com.mycompany.mavenproject1.model.Users;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class ConsultarUsuariosJPanel extends javax.swing.JPanel {
    
    private App app;

    public ConsultarUsuariosJPanel() {
        initComponents();
        carregarUsuariosNaTabela();
    }
    
    public void setApp(App app) {
    this.app = app;
    }
   
    public ConsultarUsuariosJPanel(App aThis) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Método para carregar os usuários na tabela
    public void carregarUsuariosNaTabela() {
        UsuarioDAO dao = new UsuarioDAO();
        List<Users> usuarios = dao.listarTodos();
        
    // Ordena em ordem alfabética
    usuarios.sort((u1, u2) -> u1.getNome().compareToIgnoreCase(u2.getNome()));


        DefaultTableModel modelo = (DefaultTableModel) ConsultarUsuariosjTable1.getModel();
        modelo.setRowCount(0); // Limpa as linhas da tabela antes de adicionar novos dados

        for (Users u : usuarios) {
            String tipoUsuario = u.getAdministrador() ? "Administrador" : "Comum";

            modelo.addRow(new Object[]{
                u.getNome(),
                u.getLogin(),
                tipoUsuario,
                u.getIdade(),
                u.getTipoPreferido1(),
                u.getTipoPreferido2()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultarUsuariosjTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ordemAlfabeticajButton1 = new javax.swing.JButton();
        ExcluirJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(31, 79, 144));
        setMinimumSize(new java.awt.Dimension(600, 400));

        ConsultarUsuariosjTable1.setFont(new java.awt.Font("SansSerif", 3, 14)); // NOI18N
        ConsultarUsuariosjTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Login", "Usuário", "Idade", "Favorito 1", "Favorito 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ConsultarUsuariosjTable1);

        jButton1.setBackground(new java.awt.Color(212, 51, 51));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ordemAlfabeticajButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        ordemAlfabeticajButton1.setText("Ordenar A-Z");
        ordemAlfabeticajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordemAlfabeticajButton1ActionPerformed(evt);
            }
        });

        ExcluirJButton.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        ExcluirJButton.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirJButton.setText("Excluir");
        ExcluirJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordemAlfabeticajButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExcluirJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ordemAlfabeticajButton1)
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addGap(39, 39, 39)
                        .addComponent(ExcluirJButton)))
                .addGap(0, 100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ordemAlfabeticajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordemAlfabeticajButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordemAlfabeticajButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        app.getCardLayout().show(app.getContainer(), "Admin");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExcluirJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ConsultarUsuariosjTable1;
    private javax.swing.JButton ExcluirJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ordemAlfabeticajButton1;
    // End of variables declaration//GEN-END:variables
}
