/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;

import javax.swing.*;
import com.mycompany.mavenproject1.App;
import com.mycompany.mavenproject1.dao.*;
import com.mycompany.mavenproject1.model.*;

/**
 *
 * @author jogar
 */
public class LoginTelaPanel extends javax.swing.JPanel {

    private App app;  // ✅ Mantém a referência ao App para controle do CardLayout

    // ✅ Construtor ajustado para receber App
    public LoginTelaPanel(App app) {
        this.app = app;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuariojLabel1 = new javax.swing.JLabel();
        EntradaUsuariojTextField1 = new javax.swing.JTextField();
        SenhajLabel1 = new javax.swing.JLabel();
        EntradaSenhajPasswordField1 = new javax.swing.JPasswordField();
        LoginjButton1 = new javax.swing.JButton();
        SairLoginjButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        UsuariojLabel1.setText("Usuário");

        EntradaUsuariojTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaUsuariojTextField1ActionPerformed(evt);
            }
        });

        SenhajLabel1.setText("Senha");

        EntradaSenhajPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaSenhajPasswordField1ActionPerformed(evt);
            }
        });

        LoginjButton1.setText("Login");
        LoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginjButton1ActionPerformed(evt);
            }
        });

        SairLoginjButton1.setText("Sair");
        SairLoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairLoginjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(UsuariojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntradaUsuariojTextField1)
                        .addComponent(SenhajLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EntradaSenhajPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(LoginjButton1))
                .addGap(42, 42, 42)
                .addComponent(SairLoginjButton1)
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(UsuariojLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntradaUsuariojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhajLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EntradaSenhajPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginjButton1)
                    .addComponent(SairLoginjButton1))
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaSenhajPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaSenhajPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaSenhajPasswordField1ActionPerformed

    private void LoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginjButton1ActionPerformed
        String senhaDigitada = new String(EntradaSenhajPasswordField1.getPassword());
        String usuarioDigitado = EntradaUsuariojTextField1.getText();
        
        UsuarioDAO daoUser = new UsuarioDAO();
        Users usuario = daoUser.BuscarUsuario(usuarioDigitado, senhaDigitada);
        
        
        if (usuario != null && usuario.getSenha().equals(senhaDigitada) && usuario.getLogin().equals(usuarioDigitado)) {
            if (usuario.getAdministrador() == true) {
                app.getCardLayout().show(app.getContainer(), "Admin");
            } else if (usuario.getAdministrador() == false){
                app.getCardLayout().show(app.getContainer(), "Usuario");
                }
            } else if (usuario == null){
                JOptionPane.showMessageDialog(null, "Usuario nao encontrado.");
        }
    }//GEN-LAST:event_LoginjButton1ActionPerformed

    private void SairLoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairLoginjButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairLoginjButton1ActionPerformed

    private void EntradaUsuariojTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaUsuariojTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaUsuariojTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField EntradaSenhajPasswordField1;
    private javax.swing.JTextField EntradaUsuariojTextField1;
    private javax.swing.JButton LoginjButton1;
    private javax.swing.JButton SairLoginjButton1;
    private javax.swing.JLabel SenhajLabel1;
    private javax.swing.JLabel UsuariojLabel1;
    // End of variables declaration//GEN-END:variables
}
