/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.mavenproject1.view;

import java.awt.Image;
import javax.swing.*;

import com.mycompany.mavenproject1.*;
import com.mycompany.mavenproject1.dao.*;
import com.mycompany.mavenproject1.model.*;

public class LoginTelaPanel extends javax.swing.JPanel {

    private App app;  

    public LoginTelaPanel(App app) {
        this.app = app;
        initComponents();
        limparCampo();
        ImageIcon icon = new ImageIcon(getClass().getResource("/images/Logo.png"));
        Image img = icon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
        labelLogo.setIcon(new ImageIcon(img)); 
        
        labelLogo.setHorizontalAlignment(SwingConstants.CENTER);
        labelLogo.setVerticalAlignment(SwingConstants.CENTER);
        
    }
    
    private void limparCampo(){
        EntradaSenhajPasswordField1.setText("");
    }

    private boolean validarCampos() {
        if (EntradaUsuariojTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Usuário é obrigatório.");
        
            return false;
        }
        if (EntradaSenhajPasswordField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Senha é obrigatório.");
        
            return false; // Impede o salvamento se nenhuma checkbox estiver selecionada
        }
            return true;
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsuariojLabel1 = new javax.swing.JLabel();
        EntradaUsuariojTextField1 = new javax.swing.JTextField();
        SenhaLoginjLabel1 = new javax.swing.JLabel();
        EntradaSenhajPasswordField1 = new javax.swing.JPasswordField();
        LoginjButton1 = new javax.swing.JButton();
        SairLoginjButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));

        UsuariojLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        UsuariojLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UsuariojLabel1.setText("Usuário");
        UsuariojLabel1.setMaximumSize(new java.awt.Dimension(40, 40));
        UsuariojLabel1.setMinimumSize(new java.awt.Dimension(40, 40));
        UsuariojLabel1.setName(""); // NOI18N
        UsuariojLabel1.setPreferredSize(new java.awt.Dimension(80, 20));

        EntradaUsuariojTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        EntradaUsuariojTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        EntradaUsuariojTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaUsuariojTextField1ActionPerformed(evt);
            }
        });

        SenhaLoginjLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        SenhaLoginjLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SenhaLoginjLabel1.setText("Senha");

        EntradaSenhajPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        EntradaSenhajPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntradaSenhajPasswordField1ActionPerformed(evt);
            }
        });

        LoginjButton1.setBackground(new java.awt.Color(87, 176, 109));
        LoginjButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LoginjButton1.setForeground(new java.awt.Color(255, 255, 255));
        LoginjButton1.setText("Login");
        LoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginjButton1ActionPerformed(evt);
            }
        });

        SairLoginjButton1.setBackground(new java.awt.Color(212, 51, 51));
        SairLoginjButton1.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        SairLoginjButton1.setForeground(new java.awt.Color(255, 255, 255));
        SairLoginjButton1.setText("Sair");
        SairLoginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairLoginjButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(31, 79, 144));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Booki");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EntradaUsuariojTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(EntradaSenhajPasswordField1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoginjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SairLoginjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(UsuariojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SenhaLoginjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(UsuariojLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaUsuariojTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(SenhaLoginjLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EntradaSenhajPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginjButton1)
                    .addComponent(SairLoginjButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaSenhajPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaSenhajPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaSenhajPasswordField1ActionPerformed

    private void LoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginjButton1ActionPerformed

            String senhaDigitada = new String(EntradaSenhajPasswordField1.getPassword());
            String usuarioDigitado = EntradaUsuariojTextField1.getText();
        
        UsuarioDAO daoUser = new UsuarioDAO();
        Users usuario = daoUser.BuscarUsuario(usuarioDigitado, senhaDigitada);
        
        if (validarCampos()) {
            if (usuario != null && usuario.getSenha().equals(senhaDigitada) && usuario.getLogin().equals(usuarioDigitado)) {
                                  
                if (usuario.getAdministrador() == true) {               
                    app.getCardLayout().show(app.getContainer(), "Admin");
                    limparCampo();
                    Sessao.setIdUsuario(usuario.getId());

                } else if (usuario.getAdministrador() == false){ 
                    app.getCardLayout().show(app.getContainer(), "Usuario");
                    limparCampo();
                    Sessao.setIdUsuario(usuario.getId());
                }
                } else if (usuario == null){
                    JOptionPane.showMessageDialog(null, "Usuario nao encontrado.");
                }                
        }
    }//GEN-LAST:event_LoginjButton1ActionPerformed

    private void SairLoginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairLoginjButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairLoginjButton1ActionPerformed

    private void EntradaUsuariojTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntradaUsuariojTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaUsuariojTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField EntradaSenhajPasswordField1;
    private javax.swing.JTextField EntradaUsuariojTextField1;
    private javax.swing.JButton LoginjButton1;
    private javax.swing.JButton SairLoginjButton1;
    private javax.swing.JLabel SenhaLoginjLabel1;
    private javax.swing.JLabel UsuariojLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogo;
    // End of variables declaration//GEN-END:variables

}
