package com.mycompany.mavenproject1.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author jogar
 */
public class UsuarioJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsuarioJPanel
     */
    public UsuarioJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BemVindojLabel2 = new javax.swing.JLabel();
        CadastrarLivrojButton1 = new javax.swing.JButton();
        VisualizarLivrosjButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setRequestFocusEnabled(false);

        BemVindojLabel2.setText("Bem Vindo!");

        CadastrarLivrojButton1.setText("Cadastrar Livro");

        VisualizarLivrosjButton1.setText("Visualizar Livros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BemVindojLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CadastrarLivrojButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VisualizarLivrosjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BemVindojLabel2)
                .addGap(61, 61, 61)
                .addComponent(CadastrarLivrojButton1)
                .addGap(18, 18, 18)
                .addComponent(VisualizarLivrosjButton1)
                .addGap(0, 259, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BemVindojLabel2;
    private javax.swing.JButton CadastrarLivrojButton1;
    private javax.swing.JButton VisualizarLivrosjButton1;
    // End of variables declaration//GEN-END:variables
}
